### ISSUE TITLE
mpnimport: Video alt-text string is reversed

### ISSUE THREAD

**Issue by stephenangelico** [AshyPC/OHP-HTML#6]
Line in MPN:

> Video - The Bible in Australia (MS) (part of Mission Spot)

Output:
`<source src="..." alt=")topS noissiM fo trap( )SM( ailartsuA ni elbiB ehT">`

**Comment by Rosuav** [comment]
The problem here is an ambiguity in the meaning of parenthesized text. I'm going to change the definition: if there's parenthesized uppercase letters (eg `(MS)`), that terminates the title, regardless of what follows.

**Comment by stephenangelico** [comment]
Then there needs to be a way of adding comments to a line.

**Comment by Rosuav** [comment]
After the person tag. Like in current MPN.
