### ISSUE TITLE
Feature request: keybinding to snap to first slide

### ISSUE THREAD

**Issue by stephenangelico** [AshyPC/OHP-HTML#7]
If it can be done in the present system without the same issue as for skipping slides, it would be nice as it gives me a clean way to run through the hymns live before the service and then snap back to the Welcome slide after the musicians do their pre-service run. `Home` is probably a suitable key that makes sense and is out of the way of accidental keypresses (assuming no editing programs need it and are running).

**Comment by Rosuav** [comment]
Done. And if you hit it by mistake, hit Ctrl-Z to jump back.
